
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView ChatWindow;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Entry ChatEntry;
	
	private global::Gtk.Button SendButton;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.DrawingArea RecieveCanvas;
	
	private global::Gtk.DrawingArea SendingCanvas;
	
	private global::Gtk.Button SendCanvasButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.ChatWindow = new global::Gtk.TextView ();
		this.ChatWindow.Buffer.Text = "##LewdChat A1##\n";
		this.ChatWindow.CanFocus = true;
		this.ChatWindow.Name = "ChatWindow";
		this.ChatWindow.Editable = false;
		this.ChatWindow.CursorVisible = false;
		this.ChatWindow.AcceptsTab = false;
		this.GtkScrolledWindow.Add (this.ChatWindow);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
		w2.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.ChatEntry = new global::Gtk.Entry ();
		this.ChatEntry.CanFocus = true;
		this.ChatEntry.Name = "ChatEntry";
		this.ChatEntry.IsEditable = true;
		this.ChatEntry.InvisibleChar = '●';
		this.hbox2.Add (this.ChatEntry);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ChatEntry]));
		w3.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.SendButton = new global::Gtk.Button ();
		this.SendButton.CanFocus = true;
		this.SendButton.Name = "SendButton";
		this.SendButton.UseUnderline = true;
		this.SendButton.Label = global::Mono.Unix.Catalog.GetString ("Send");
		global::Gtk.Image w4 = new global::Gtk.Image ();
		w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
		this.SendButton.Image = w4;
		this.hbox2.Add (this.SendButton);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.SendButton]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w7.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.RecieveCanvas = new global::Gtk.DrawingArea ();
		this.RecieveCanvas.WidthRequest = 300;
		this.RecieveCanvas.HeightRequest = 300;
		this.RecieveCanvas.Name = "RecieveCanvas";
		this.vbox3.Add (this.RecieveCanvas);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.RecieveCanvas]));
		w8.Position = 0;
		// Container child vbox3.Gtk.Box+BoxChild
		this.SendingCanvas = new global::Gtk.DrawingArea ();
		this.SendingCanvas.WidthRequest = 300;
		this.SendingCanvas.HeightRequest = 300;
		this.SendingCanvas.Name = "SendingCanvas";
		this.vbox3.Add (this.SendingCanvas);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.SendingCanvas]));
		w9.Position = 1;
		// Container child vbox3.Gtk.Box+BoxChild
		this.SendCanvasButton = new global::Gtk.Button ();
		this.SendCanvasButton.CanFocus = true;
		this.SendCanvasButton.Name = "SendCanvasButton";
		this.SendCanvasButton.UseUnderline = true;
		this.SendCanvasButton.Label = global::Mono.Unix.Catalog.GetString ("Send Canvas");
		global::Gtk.Image w10 = new global::Gtk.Image ();
		w10.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
		this.SendCanvasButton.Image = w10;
		this.vbox3.Add (this.SendCanvasButton);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.SendCanvasButton]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.hbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 914;
		this.DefaultHeight = 637;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
