
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FriendsListAction;
	
	private global::Gtk.Action OptionsAction;
	
	private global::Gtk.Action addAction;
	
	private global::Gtk.Action SettingsAction;
	
	private global::Gtk.Action ViewMyKeyAction;
	
	private global::Gtk.Action ContactsAction;
	
	private global::Gtk.Action newAction;
	
	private global::Gtk.Action removeAction;
	
	private global::Gtk.Action SettingsAction1;
	
	private global::Gtk.Action findAction;
	
	private global::Gtk.Action editAction1;
	
	private global::Gtk.Action editAction;
	
	private global::Gtk.Action propertiesAction1;
	
	private global::Gtk.Action propertiesAction2;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.TreeView FriendList;
	
	private global::Gtk.Statusbar statusbar1;
	
	private global::Gtk.Label StatusLabel;
	
	private global::Gtk.Image StatusIcon;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FriendsListAction = new global::Gtk.Action ("FriendsListAction", global::Mono.Unix.Catalog.GetString ("Friends List"), null, null);
		this.FriendsListAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Friends List");
		w1.Add (this.FriendsListAction, null);
		this.OptionsAction = new global::Gtk.Action ("OptionsAction", global::Mono.Unix.Catalog.GetString ("Options"), null, null);
		this.OptionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Options");
		w1.Add (this.OptionsAction, null);
		this.addAction = new global::Gtk.Action ("addAction", global::Mono.Unix.Catalog.GetString ("Add Friend..."), global::Mono.Unix.Catalog.GetString ("Add other losers to draw with!"), "gtk-add");
		this.addAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Friend...");
		w1.Add (this.addAction, null);
		this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
		w1.Add (this.SettingsAction, null);
		this.ViewMyKeyAction = new global::Gtk.Action ("ViewMyKeyAction", global::Mono.Unix.Catalog.GetString ("View my Key"), null, null);
		this.ViewMyKeyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View my Key");
		w1.Add (this.ViewMyKeyAction, null);
		this.ContactsAction = new global::Gtk.Action ("ContactsAction", global::Mono.Unix.Catalog.GetString ("Contacts"), null, null);
		this.ContactsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Contacts");
		w1.Add (this.ContactsAction, null);
		this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("Add Friend"), null, "gtk-new");
		this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Friend");
		w1.Add (this.newAction, null);
		this.removeAction = new global::Gtk.Action ("removeAction", global::Mono.Unix.Catalog.GetString ("Delete Friend"), null, "gtk-remove");
		this.removeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Delete Friend");
		w1.Add (this.removeAction, null);
		this.SettingsAction1 = new global::Gtk.Action ("SettingsAction1", global::Mono.Unix.Catalog.GetString ("Settings"), null, null);
		this.SettingsAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
		w1.Add (this.SettingsAction1, null);
		this.findAction = new global::Gtk.Action ("findAction", global::Mono.Unix.Catalog.GetString ("See Secret Key"), null, "gtk-find");
		this.findAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("See Secret Key");
		w1.Add (this.findAction, null);
		this.editAction1 = new global::Gtk.Action ("editAction1", global::Mono.Unix.Catalog.GetString ("Change Name"), null, "gtk-edit");
		this.editAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Change Name");
		w1.Add (this.editAction1, null);
		this.editAction = new global::Gtk.Action ("editAction", global::Mono.Unix.Catalog.GetString ("Edit Friend"), null, "gtk-edit");
		this.editAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit Friend");
		w1.Add (this.editAction, null);
		this.propertiesAction1 = new global::Gtk.Action ("propertiesAction1", global::Mono.Unix.Catalog.GetString ("Notification"), null, "gtk-properties");
		this.propertiesAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Notification");
		w1.Add (this.propertiesAction1, null);
		this.propertiesAction2 = new global::Gtk.Action ("propertiesAction2", global::Mono.Unix.Catalog.GetString ("Interface"), null, "gtk-properties");
		this.propertiesAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("Interface");
		w1.Add (this.propertiesAction2, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='ContactsAction' action='ContactsAction'><menuitem name='newAction' action='newAction'/><menuitem name='removeAction' action='removeAction'/><menuitem name='editAction' action='editAction'/></menu><menu name='SettingsAction1' action='SettingsAction1'><menuitem name='findAction' action='findAction'/><menuitem name='editAction1' action='editAction1'/><menuitem name='propertiesAction1' action='propertiesAction1'/><menuitem name='propertiesAction2' action='propertiesAction2'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.FriendList = new global::Gtk.TreeView ();
		this.FriendList.CanFocus = true;
		this.FriendList.Name = "FriendList";
		this.FriendList.EnableSearch = false;
		this.vbox1.Add (this.FriendList);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.FriendList]));
		w3.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.StatusLabel = new global::Gtk.Label ();
		this.StatusLabel.Name = "StatusLabel";
		this.StatusLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Not Connected");
		this.statusbar1.Add (this.StatusLabel);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.StatusLabel]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.StatusIcon = new global::Gtk.Image ();
		this.StatusIcon.Name = "StatusIcon";
		this.StatusIcon.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-disconnect", global::Gtk.IconSize.Menu);
		this.statusbar1.Add (this.StatusIcon);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.StatusIcon]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 290;
		this.DefaultHeight = 424;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		//this.addAction.Activated += new global::System.EventHandler (this.OnAddActionActivated);
		this.newAction.Activated += new global::System.EventHandler (this.OnAddFriendActivated);
	}
}
